
include(":storage-api")
include(":grpc-reactor")
include(":jooq-utils")
include(":jooq-r2dbc")
include(":tpc:tpc-grpc-api")
include(":tpc:tpc-grpc-service")
include(":orders:orders-grpc-api")
include(":orders:orders-grpc-service")
include(":reserve:reserve-grpc-api")
include(":reserve:reserve-grpc-service")
include(":payments:payments-grpc-api")
include(":payments:payments-grpc-service")
include(":delivery")