import org.gradle.kotlin.dsl.project

include(":storage-jooq")
include(":storage-api")
include(":grpc-webflux")
include(":grpc-client")
include(":protobuf-utils")
include(":jooq-r2dbc")
include(":jooq-postgres-prepared-transaction")
include(":tpc:tpc-grpc-api")
include(":tpc:tpc-grpc-service")
include(":orders:orders-grpc-api")
include(":orders:orders-grpc-service")
include(":orders:orders-storage-r2dbc")
include(":reserve:reserve-grpc-api")
include(":reserve:reserve-grpc-service")
include(":reserve:reserve-storage-r2dbc")
include(":payments:payments-event-api")
include(":payments:payments-grpc-api")
include(":payments:payments-grpc-service")
include(":payments:payments-storage-r2dbc")
include(":idempotent-consumer")
include(":integration-test")
include(":reactive-utils")
