debug: true
logging:
  level:
    root: INFO
    org:
      springframework:
        r2dbc:
          connection: TRACE
        transaction:
          reactive: TRACE
      apache:
        tomcat:
          util:
            net:
              NioEndpoint: INFO

    io:
      github:
        m4gshm: TRACE
      grpc:
        netty:
          shaded:
            io:
              grpc:
                netty:
                  NettyClientHandler: INFO
                  NettyServerHandler: INFO
      r2dbc:
        spi: TRACE
        postgresql:
          client:
            ReactorNettyClient: INFO
          QUERY: DEBUG
    java:
      io:
        serialization: INFO
    sun:
      rmi: INFO
    javax:
      management: INFO

#spring:
#  grpc:
#    server:
#      port: 9090
server:
  port: 7081
  error:
    include-message: always
grpc:
  server:
    port: 9081
    channelz:
      enabled: false
    health:
      enabled: false #conflict with spring.grpc.server.health.enabled
    reflection:
      enabled: false
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  use-fqn: true  # Use fully qualified names for better clarity

spring:
  datasource:
    url: jdbc:postgresql://localhost:5000/reserve
    username: postgres
    password: postgres
  r2dbc:
    url: r2dbc:postgresql://localhost:5000/reserve
    username: postgres
    password: postgres
  liquibase:
    enabled: true
  kafka:
    bootstrap-servers:
      - localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: payments
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
