debug: true
logging:
  level:
    root: debug
spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5000/payment
    username: postgres
    password: postgres
service:
  orders:
    address: localhost:9080
  reserve:
    address: localhost:9081
  warehouse:
    address: localhost:9081
  payments:
    address: localhost:9082

