[workspace]
members = [
    "common",
    "proto-build",
    "orders-service",
    "payments-service", 
    "reserve-service",
    "tpc-service",
]

[workspace.dependencies]
# gRPC and async runtime
tokio = { version = "1.0", features = ["full"] }
tonic = "0.11"
tonic-build = "0.11"
tonic-reflection = "0.11"
prost = "0.12"
prost-types = "0.12"

# Database
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "postgres", "chrono", "uuid", "json"] }

# Serialization/Deserialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# UUID and time handling
uuid = { version = "1.0", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }

# Error handling and logging
anyhow = "1.0"
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Configuration
config = "0.14"

# OpenTelemetry (for observability, matching Java implementation)
opentelemetry = "0.21"
opentelemetry-jaeger = "0.20"
tracing-opentelemetry = "0.22"

# Async utilities
futures = "0.3"
async-trait = "0.1"

# Kafka (for event-driven architecture)
rdkafka = { version = "0.36", features = ["cmake-build", "ssl-vendored"] }

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Generated from Java implementation"]
license = "Apache-2.0"