debug: true
logging:
  level:
    root: INFO
    io:
      github:
        m4gshm: TRACE
      r2dbc:
        postgresql:
          QUERY: DEBUG
    java:
      io:
        serialization: INFO
    sun:
      rmi: INFO
    javax:
      management: INFO
#spring:
#  grpc:
#    server:
#      port: 9090
server:
  port: 7080
  error:
    include-message: always
grpc:
  server:
    port: 9080
    channelz:
      enabled: false
    health:
      enabled: false #conflict with spring.grpc.server.health.enabled
    reflection:
      enabled: false
    exception-handling:
      default-exception-advice-enabled: true
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  use-fqn: true  # Use fully qualified names for better clarity

spring:
  #for liquibase
  datasource:
    url: r2dbc:postgresql://localhost:5000/orders
    username: postgres
    password: postgres
  r2dbc:
    url: r2dbc:postgresql://localhost:5000/orders
    username: postgres
    password: postgres
  liquibase:
    enabled: true

service:
  reserve:
    address: localhost:9081
  warehouse:
    address: localhost:9081
  payments:
    address: localhost:9082