logging:
  level:
    root: DEBUG
    java:
      io:
        serialization: INFO
    sun:
      rmi: INFO
    javax:
      management: INFO
#spring:
#  grpc:
#    server:
#      port: 9090
server:
  port: 8080
grpc:
  server:
    port: 9080

    channelz:
      enabled: false
    health:
      enabled: false #conflict with spring.grpc.server.health.enabled
    reflection:
      enabled: false

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  use-fqn: true  # Use fully qualified names for better clarity

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/orders
    username: postgres
    password: postgres
  liquibase:
    enabled: true

service:
  reserve:
    address: localhost:9081
  payments:
    address: localhost:9082